import Link from 'next/link';
import { ArrowRight, Building2, CheckCircle2, CreditCard, LockKeyhole, ShoppingCart } from 'lucide-react';

export default function CartPage(){return <main>
<section className="bg-[#061321] py-12 text-white"><div className="container"><div className="text-[10px] font-black uppercase tracking-[.18em] text-blue-300">ProPrint Shop</div><h1 className="mt-2 text-4xl font-black tracking-[-.04em]">Your Cart</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">A production checkout will be connected when the future Shopify store is approved. This page demonstrates the intended customer journey.</p></div></section>
<section className="py-14"><div className="container grid gap-7 lg:grid-cols-[1fr_360px]">
<div className="rounded-[2rem] border border-slate-200 bg-white p-8 shadow-sm"><ShoppingCart className="text-[#0b5cff]" size={34}/><h2 className="mt-4 text-2xl font-black">Prototype shopping cart</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-600">Product selection, quantities, live stock and payment are intentionally not persisted in this management prototype. The production implementation can use Shopify for inventory, checkout and order processing while keeping the ProPrint corporate experience.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{['Live inventory & stock','Secure checkout','Kuwait delivery options'].map(x=><div key={x} className="flex gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold"><CheckCircle2 size={16} className="shrink-0 text-[#0b5cff]"/>{x}</div>)}</div><Link href="/shop" className="mt-7 inline-flex items-center rounded-full bg-[#061321] px-6 py-3 font-black text-white">Continue Shopping <ArrowRight className="ml-2" size={16}/></Link></div>
<aside className="h-fit rounded-[2rem] bg-slate-100 p-7"><h2 className="text-xl font-black">Business purchase?</h2><p className="mt-2 text-sm leading-6 text-slate-600">For multiple units, project deployment, installation or AMC, request a corporate quotation instead of standard checkout.</p><Link href="/quote" className="mt-5 flex items-center justify-center rounded-full bg-[#f47b20] px-5 py-3 font-black text-white"><Building2 className="mr-2" size={17}/>Request Quote</Link><div className="mt-6 border-t border-slate-200 pt-5 text-xs leading-6 text-slate-500"><div className="flex items-center gap-2 font-bold text-slate-700"><LockKeyhole size={15}/>Production-ready architecture</div><p className="mt-2">The future store can hand payment and order processing to Shopify while ProPrint retains its branded website and service workflows.</p></div></aside>
</div></section>
</main>}
