import Link from 'next/link';
import { Building2, CheckCircle2, Printer, Server, ShieldCheck, ShoppingBag } from 'lucide-react';
import { RequestForm } from '@/components/RequestForm';

export default async function ArabicQuotePage({ searchParams }:{ searchParams:Promise<{ product?:string; sku?:string; request?:string }> }){
 const params=await searchParams;
 const requestKind=params.request==='price'?'price':params.request==='availability'?'availability':'business';
 const hasProduct=Boolean(params.product);
 const cards=[[ShoppingBag,'المنتجات والمشتريات','طلبات منتجات تقنية المعلومات الفردية أو بالكميات.'],[Printer,'الطباعة والبلوتر','الطابعات وأجهزة MFP والبلوتر والمستلزمات.'],[ShieldCheck,'عقود الصيانة والخدمة','الصيانة الوقائية واتفاقيات الدعم.'],[Server,'تقنية المعلومات للشركات','التجهيز والدعم في الموقع والخدمات الميدانية.']] as const;
 return <main dir="rtl" lang="ar" className="text-right">
<section className="bg-[#0b5cff] py-16 text-white"><div className="container"><div className="text-[11px] font-black tracking-[.18em] text-blue-100">الأعمال والشركات</div><h1 className="mt-3 text-5xl font-black tracking-[-.04em] md:text-6xl">اطلب عرض سعر من ProPrint.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-blue-100">للمنتجات ومشتريات الشركات وعقود الصيانة وحلول الطباعة والتجهيز وخدمات تقنية المعلومات الميدانية — مسار واحد لمتطلبات أعمالك.</p></div></section>
<section className="py-14"><div className="container grid gap-5 md:grid-cols-2 lg:grid-cols-4">{cards.map(([Icon,title,text])=><div key={title} className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><Icon className="text-[#0b5cff]"/><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>)}</div></section>
<section id="request" className="scroll-mt-6 bg-slate-50 py-16"><div className="container"><div className="mb-6 rounded-2xl border border-blue-100 bg-blue-50 px-5 py-4 text-sm font-bold text-slate-700">{hasProduct?'تمت إضافة المنتج المحدد إلى النموذج أدناه. أضف بيانات التواصل والكمية وأي متطلبات إضافية.':'أنت في المكان الصحيح. أكمل طلب عرض السعر أدناه وأضف تفاصيل المنتج أو الخدمة أو عقد الصيانة أو متطلبات الشركات.'}</div><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><Building2 className="text-[#0b5cff]" size={37}/><h2 className="mt-5 text-3xl font-black">أخبرنا بما تحتاج إليه.</h2><p className="mt-3 leading-7 text-slate-600">أرسل متطلباتك أدناه. سيقوم الموقع بإنشاء رقم مرجعي لطلب عرض السعر لتوجيه الطلب إلى فريق ProPrint المناسب.</p><div className="mt-7 space-y-3">{['أسعار الشركات والكميات','التركيب ونطاق التجهيز','متطلبات عقود الصيانة','الدعم الفني للشركات في الموقع'].map(x=><div key={x} className="text-sm font-bold"><CheckCircle2 className="ml-2 inline text-[#0b5cff]" size={17}/>{x}</div>)}</div></div><RequestForm mode="quote" product={params.product??''} sku={params.sku??''} requestKind={requestKind}/></div></div></section>
<section className="py-14"><div className="container flex flex-col gap-5 rounded-[2rem] bg-[#061321] p-8 text-white md:flex-row md:items-center md:justify-between"><div><h2 className="text-2xl font-black">هل تحتاج إلى صيانة فنية بدلاً من ذلك؟</h2><p className="mt-2 text-sm text-slate-300">استخدم مركز خدمات ProPrint للإصلاح والتشخيص والدعم الفني.</p></div><Link href="/ar/service#request" className="inline-flex rounded-full bg-white px-6 py-3 font-black text-[#061321]">الانتقال إلى طلب الصيانة</Link></div></section>
</main>}