import Link from 'next/link';
import { CheckCircle2, Clock3, Headphones, MapPin, ShieldCheck, Wrench } from 'lucide-react';
import { RequestForm } from '@/components/RequestForm';

const capabilities=['Printer & Plotter Repair','Laptop & Desktop Repair','Hardware Diagnostics','Installation & Configuration','Preventive Maintenance','Warranty & Spare Parts Support','Onsite Business Support','AMC'];

export default function ServicePage(){return <main>
<section className="bg-[#061321] py-16 text-white"><div className="container grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><div className="text-[11px] font-black uppercase tracking-[.18em] text-blue-200">ProPrint Service Center</div><h1 className="mt-3 text-5xl font-black tracking-[-.04em] md:text-6xl">Professional technical support.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">Printers, plotters, laptops, PCs and business hardware — diagnosis, repair, installation, maintenance and onsite support across Kuwait.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="#request" className="rounded-full bg-[#0b5cff] px-6 py-3.5 font-black text-white">Request Service</Link><Link href="/amc" className="rounded-full bg-[#f47b20] px-6 py-3.5 font-black text-white">Explore AMC</Link></div></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.05] p-5"><Wrench/><h3 className="mt-5 font-black">Technical Repair</h3><p className="mt-2 text-sm leading-6 text-slate-300">Diagnosis, repair and parts replacement.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.05] p-5"><MapPin/><h3 className="mt-5 font-black">Onsite Support</h3><p className="mt-2 text-sm leading-6 text-slate-300">Business support at customer locations.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.05] p-5"><Clock3/><h3 className="mt-5 font-black">Preventive Care</h3><p className="mt-2 text-sm leading-6 text-slate-300">Maintenance designed to reduce downtime.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.05] p-5"><ShieldCheck/><h3 className="mt-5 font-black">AMC Coverage</h3><p className="mt-2 text-sm leading-6 text-slate-300">Ongoing support plans for business equipment.</p></div></div></div></section>

<section className="py-16"><div className="container"><div className="grid gap-10 lg:grid-cols-[.95fr_1.05fr]"><div><div className="text-[11px] font-black uppercase tracking-[.18em] text-[#0b5cff]">Service capabilities</div><h2 className="mt-3 text-4xl font-black tracking-[-.03em]">Support beyond the sale.</h2><p className="mt-4 max-w-xl leading-7 text-slate-600">ProPrint combines workshop repair, field support and long-term maintenance services so customers have one technology partner after purchase.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{capabilities.map(x=><div key={x} className="rounded-2xl border border-slate-200 bg-white p-4 font-bold shadow-sm"><CheckCircle2 className="mr-2 inline text-[#0b5cff]" size={17}/>{x}</div>)}</div></div><div className="rounded-[2rem] bg-slate-100 p-8"><Headphones className="text-[#0b5cff]" size={36}/><h3 className="mt-5 text-2xl font-black">Business support workflow</h3><div className="mt-6 space-y-4">{[['01','Request logged'],['02','Diagnosis / technician assignment'],['03','Repair or onsite action'],['04','Testing and customer update']].map(([n,t])=><div key={n} className="flex items-center gap-4 rounded-2xl bg-white p-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#0b5cff] text-xs font-black text-white">{n}</div><b>{t}</b></div>)}</div></div></div></div></section>

<section id="request" className="scroll-mt-6 bg-slate-50 py-16"><div className="container max-w-5xl"><div className="mb-6 rounded-2xl border border-blue-100 bg-blue-50 px-5 py-4 text-sm font-bold text-slate-700">Ready to continue? Complete the service request below and ProPrint will receive the equipment and fault details once live delivery is enabled.</div><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><div className="text-[11px] font-black uppercase tracking-[.18em] text-[#0b5cff]">Need assistance?</div><h2 className="mt-3 text-4xl font-black">Request Service</h2><p className="mt-4 leading-7 text-slate-600">Submit the equipment and fault details below. The website now creates a service reference number and can route the request to ProPrint by email or webhook once the production delivery setting is enabled.</p></div><RequestForm mode="service"/></div></div></section>
</main>}
