import Link from 'next/link';
import { CheckCircle2, Clock3, Printer, Server, ShieldCheck, Wrench } from 'lucide-react';

const plans=[
  {title:'Printer & Plotter AMC',text:'Preventive maintenance and support for office printers, MFPs and large-format equipment.',icon:Printer},
  {title:'PC & Laptop AMC',text:'Business endpoint maintenance, break/fix support and scheduled preventive care.',icon:Wrench},
  {title:'Infrastructure AMC',text:'Support coverage for selected servers, storage, networking and business hardware.',icon:Server},
];

export default function AmcPage(){return <main>
<section className="bg-gradient-to-br from-[#061321] to-[#0b5cff] py-16 text-white"><div className="container"><div className="max-w-4xl"><div className="text-[11px] font-black uppercase tracking-[.18em] text-blue-200">Annual Maintenance Contracts</div><h1 className="mt-3 text-5xl font-black tracking-[-.04em] md:text-6xl">Keep your technology running.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-blue-100">Flexible maintenance and support agreements for printing equipment, endpoints and selected business IT infrastructure.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/quote" className="rounded-full bg-[#f47b20] px-6 py-3.5 font-black text-white">Request AMC Proposal</Link><Link href="/service" className="rounded-full border border-white/20 bg-white/[.06] px-6 py-3.5 font-black text-white">Service Center</Link></div></div></div></section>
<section className="py-16"><div className="container"><div className="text-[11px] font-black uppercase tracking-[.18em] text-[#0b5cff]">Coverage options</div><h2 className="mt-3 text-4xl font-black tracking-[-.03em]">Support plans built around your environment.</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{plans.map(({title,text,icon:Icon})=><div key={title} className="rounded-[1.7rem] border border-slate-200 bg-white p-7 shadow-sm"><Icon className="text-[#0b5cff]" size={31}/><h3 className="mt-6 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></div>)}</div></div></section>
<section className="bg-slate-100 py-16"><div className="container grid gap-8 lg:grid-cols-[1fr_.9fr]"><div><div className="text-[11px] font-black uppercase tracking-[.18em] text-[#0b5cff]">Typical AMC services</div><h2 className="mt-3 text-4xl font-black tracking-[-.03em]">Prevent. Support. Maintain.</h2><div className="mt-7 grid gap-3 sm:grid-cols-2">{['Scheduled preventive maintenance','Break/fix support','Onsite visits where applicable','Hardware health checks','Service reporting','Priority support options','Parts coordination where applicable','Asset support planning'].map(x=><div key={x} className="rounded-2xl bg-white p-4 text-sm font-bold shadow-sm"><CheckCircle2 className="mr-2 inline text-[#0b5cff]" size={17}/>{x}</div>)}</div></div><div className="rounded-[2rem] bg-[#061321] p-8 text-white"><ShieldCheck size={39}/><h3 className="mt-6 text-3xl font-black">Why AMC?</h3><p className="mt-4 leading-7 text-slate-300">A maintenance agreement gives businesses a predictable support framework and helps reduce avoidable downtime through regular preventive care.</p><div className="mt-7 rounded-2xl bg-white/[.07] p-5"><Clock3 className="text-blue-300"/><b className="mt-3 block">Flexible scope</b><p className="mt-2 text-sm leading-6 text-slate-300">Final SLA, response times, covered assets, parts terms and visit frequency are defined in the commercial proposal.</p></div></div></div></section>
<section className="py-16"><div className="container rounded-[2rem] bg-[#0b5cff] p-9 text-white md:flex md:items-center md:justify-between"><div><h2 className="text-3xl font-black">Need an AMC for your business?</h2><p className="mt-2 text-blue-100">Tell us what equipment you have and the level of support you need.</p></div><Link href="/quote" className="mt-6 inline-flex rounded-full bg-[#f47b20] px-6 py-3.5 font-black text-white md:mt-0">Request AMC Proposal</Link></div></section>
</main>}
