import Link from 'next/link';
import { Building2, Clock3, Mail, MapPin, Phone, ShoppingBag, Wrench } from 'lucide-react';

export default function ContactPage(){return <main>
<section className="bg-[#0b5cff] py-16 text-white"><div className="container"><div className="text-[11px] font-black uppercase tracking-[.18em] text-blue-100">Contact ProPrint</div><h1 className="mt-3 text-5xl font-black tracking-[-.04em] md:text-6xl">Talk to the right ProPrint team.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-blue-100">Product enquiries, repair requests, AMC, printing solutions and enterprise IT requirements — choose the route that best fits what you need.</p></div></section>

<section className="py-16"><div className="container grid gap-5 md:grid-cols-2 lg:grid-cols-4"><div className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><Mail className="text-[#0b5cff]"/><h3 className="mt-5 font-black">Email</h3><p className="mt-2 text-sm leading-6 text-slate-600">support@proprintsolutions.net</p></div><div className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><Phone className="text-[#0b5cff]"/><h3 className="mt-5 font-black">Phone</h3><p className="mt-2 text-sm leading-6 text-slate-600">+965 24333201</p></div><div className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><MapPin className="text-[#0b5cff]"/><h3 className="mt-5 font-black">Location</h3><p className="mt-2 text-sm leading-6 text-slate-600">Galleria Building 57, behind Lulu, Mezzanine Office No. 1, Gate #3, Al-Dajeej 13095, Kuwait</p></div><div className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><Clock3 className="text-[#0b5cff]"/><h3 className="mt-5 font-black">Working Hours</h3><p className="mt-2 text-sm leading-6 text-slate-600">Sunday–Thursday: 8:00 AM–5:00 PM<br/>Saturday: 8:00 AM–2:00 PM<br/>Friday: Closed</p></div></div></section>

<section className="bg-slate-50 py-16"><div className="container"><div className="grid gap-6 lg:grid-cols-3"><Link href="/shop" className="rounded-[2rem] border border-slate-200 bg-white p-8 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><ShoppingBag className="text-[#0b5cff]" size={32}/><h2 className="mt-6 text-2xl font-black">Product Enquiry</h2><p className="mt-3 text-sm leading-6 text-slate-600">Browse the ProPrint shop prototype for laptops, printers, plotters, networking, storage and accessories.</p><span className="mt-6 inline-block text-sm font-black text-[#0b5cff]">Browse products →</span></Link><Link href="/service" className="rounded-[2rem] border border-slate-200 bg-white p-8 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><Wrench className="text-[#0b5cff]" size={32}/><h2 className="mt-6 text-2xl font-black">Repair / Technical Service</h2><p className="mt-3 text-sm leading-6 text-slate-600">Submit a repair, diagnostics, installation or onsite-support request through the Service Center.</p><span className="mt-6 inline-block text-sm font-black text-[#0b5cff]">Request service →</span></Link><Link href="/quote" className="rounded-[2rem] bg-[#061321] p-8 text-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><Building2 className="text-blue-300" size={32}/><h2 className="mt-6 text-2xl font-black">Business / Corporate Quote</h2><p className="mt-3 text-sm leading-6 text-slate-300">Use the quote workflow for bulk procurement, AMC, printing projects or enterprise field-service requirements.</p><span className="mt-6 inline-block text-sm font-black text-blue-300">Request a quote →</span></Link></div><div className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-900"><b>Management demo:</b> request forms currently demonstrate the complete workflow and generate ProPrint reference numbers. Live email delivery will be activated after domain/DNS access is approved.</div></div></section>
</main>}
