import Link from 'next/link';
import { Building2, CheckCircle2, Printer, Server, ShieldCheck, ShoppingBag } from 'lucide-react';
import { RequestForm } from '@/components/RequestForm';

export default function QuotePage(){return <main>
<section className="bg-[#0b5cff] py-16 text-white"><div className="container"><div className="text-[11px] font-black uppercase tracking-[.18em] text-blue-100">Business & Enterprise</div><h1 className="mt-3 text-5xl font-black tracking-[-.04em] md:text-6xl">Request a ProPrint quote.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-blue-100">Products, corporate procurement, AMC, printing solutions, deployment or enterprise field services — one enquiry route for business requirements.</p></div></section>
<section className="py-14"><div className="container grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[[ShoppingBag,'Products & Procurement','Single or bulk IT product requirements.'],[Printer,'Printing & Plotting','Printers, MFPs, plotters and supplies.'],[ShieldCheck,'AMC & Service','Preventive maintenance and support agreements.'],[Server,'Enterprise IT','Deployment, onsite support and field services.']].map(([Icon,title,text])=>{const I=Icon as any;return <div key={title as string} className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><I className="text-[#0b5cff]"/><h3 className="mt-5 font-black">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text as string}</p></div>})}</div></section>
<section id="request" className="scroll-mt-6 bg-slate-50 py-16"><div className="container"><div className="mb-6 rounded-2xl border border-blue-100 bg-blue-50 px-5 py-4 text-sm font-bold text-slate-700">You’re in the right place. Complete the quotation request below and include the product, service, AMC or enterprise requirement you selected.</div><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><Building2 className="text-[#0b5cff]" size={37}/><h2 className="mt-5 text-3xl font-black">Tell us what you need.</h2><p className="mt-3 leading-7 text-slate-600">Submit your requirement below. The website now generates a quote reference number and can route the enquiry to ProPrint sales, service, AMC or enterprise teams once production email/webhook delivery is enabled.</p><div className="mt-7 space-y-3">{['Corporate / bulk pricing','Installation and deployment scope','AMC requirements','Enterprise onsite support'].map(x=><div key={x} className="text-sm font-bold"><CheckCircle2 className="mr-2 inline text-[#0b5cff]" size={17}/>{x}</div>)}</div></div><RequestForm mode="quote"/></div></div></section>
<section className="py-14"><div className="container flex flex-col gap-5 rounded-[2rem] bg-[#061321] p-8 text-white md:flex-row md:items-center md:justify-between"><div><h2 className="text-2xl font-black">Need technical service instead?</h2><p className="mt-2 text-sm text-slate-300">Use the ProPrint Service Center flow for repair, diagnostics or technical support.</p></div><Link href="/service#request" className="inline-flex rounded-full bg-white px-6 py-3 font-black text-[#061321]">Go to Service Request</Link></div></section>
</main>}
