import Link from 'next/link';
import { Building2, CheckCircle2, Headphones, Printer, Server, ShieldCheck, ShoppingBag, Wrench } from 'lucide-react';

const capabilities = [
  ['IT Products','Laptops, desktops, monitors, networking, storage, UPS and accessories.',ShoppingBag],
  ['Printing & Plotting','Printers, MFPs, plotters, consumables and large-format solutions.',Printer],
  ['Service Center','Diagnostics, repair, installation, configuration and preventive maintenance.',Wrench],
  ['AMC','Ongoing maintenance and support coverage for business equipment.',ShieldCheck],
  ['Enterprise IT','Onsite field support, deployment, IMAC and hardware break/fix capability.',Server],
  ['Business Support','One enquiry route for procurement, service, AMC and enterprise requirements.',Headphones],
] as const;

export default function AboutPage(){return <main>
<section className="bg-[#061321] py-16 text-white"><div className="container grid gap-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><div className="text-[11px] font-black uppercase tracking-[.18em] text-blue-200">About ProPrint Solutions</div><h1 className="mt-3 text-5xl font-black tracking-[-.04em] md:text-6xl">Technology supply backed by technical capability.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">ProPrint Solutions brings together IT products, professional printing, technical service, AMC and enterprise field support for customers in Kuwait.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/shop" className="rounded-full bg-[#0b5cff] px-6 py-3.5 font-black text-white">Explore Products</Link><Link href="/quote" className="rounded-full bg-[#f47b20] px-6 py-3.5 font-black text-white">Request a Quote</Link></div></div><div className="rounded-[2rem] border border-white/10 bg-white/[.05] p-8"><Building2 size={38} className="text-blue-300"/><h2 className="mt-5 text-2xl font-black">One ProPrint experience</h2><p className="mt-3 leading-7 text-slate-300">From a single business laptop or printer to a larger deployment, ProPrint is positioned to support the product, service and lifecycle requirements around the technology.</p><div className="mt-6 space-y-3">{['Product supply','Installation & deployment','Repair & technical support','Preventive maintenance','AMC & onsite support'].map(x=><div key={x} className="text-sm font-bold text-slate-200"><CheckCircle2 className="mr-2 inline text-blue-400" size={17}/>{x}</div>)}</div></div></div></section>

<section className="py-16"><div className="container"><div className="text-center"><div className="text-[11px] font-black uppercase tracking-[.18em] text-[#0b5cff]">Our capability</div><h2 className="mt-3 text-4xl font-black tracking-[-.03em]">More than an IT product seller.</h2><p className="mx-auto mt-4 max-w-3xl leading-7 text-slate-600">The 2026 platform is designed around the full customer journey: discover products, request technical service, plan AMC coverage and engage ProPrint for enterprise support.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{capabilities.map(([title,text,Icon])=><div key={title} className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><Icon className="text-[#0b5cff]"/><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>)}</div></div></section>

<section className="bg-slate-100 py-16"><div className="container grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="text-[11px] font-black uppercase tracking-[.18em] text-[#0b5cff]">Built for Kuwait</div><h2 className="mt-3 text-4xl font-black tracking-[-.03em]">Sales, service and field support in one platform.</h2><p className="mt-4 max-w-3xl leading-7 text-slate-600">The new ProPrint website is being built to serve both retail and business customers while keeping technical support, service requests and corporate enquiries connected to the same brand experience.</p></div><div className="flex flex-wrap gap-3"><Link href="/service" className="rounded-full bg-[#061321] px-6 py-3.5 font-black text-white">Service Center</Link><Link href="/enterprise" className="rounded-full bg-[#0b5cff] px-6 py-3.5 font-black text-white">Enterprise IT</Link></div></div></section>
</main>}
