'use server';

import { redirect } from 'next/navigation';
import { revalidatePath } from 'next/cache';
import { createSupabaseServerClient } from '@/lib/supabase/server';

const PRODUCT_IMAGE_BUCKET = 'product-images';
const MAX_IMAGE_SIZE = 5 * 1024 * 1024;
const MAX_PRODUCT_IMAGES = 5;
const ALLOWED_IMAGE_TYPES = new Set(['image/jpeg', 'image/png', 'image/webp']);
function optionalText(value: FormDataEntryValue | null){const text=String(value??'').trim();return text||null;}
function optionalNumber(value: FormDataEntryValue | null){const text=String(value??'').trim();if(!text)return null;const number=Number(text);return Number.isFinite(number)?number:null;}
function imageExtension(file:File){switch(file.type){case'image/jpeg':return'jpg';case'image/png':return'png';case'image/webp':return'webp';default:return null;}}
async function requireAdmin(){const supabase=await createSupabaseServerClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/admin/login');const{data:isAdmin}=await supabase.rpc('is_admin');if(!isAdmin)redirect('/admin/login?error=unauthorized');return supabase;}
function storagePathFromPublicUrl(url:string){try{const parsed=new URL(url);const marker=`/storage/v1/object/public/${PRODUCT_IMAGE_BUCKET}/`;const index=parsed.pathname.indexOf(marker);return index>=0?decodeURIComponent(parsed.pathname.slice(index+marker.length)):null;}catch{return null;}}
async function uploadImages(supabase:Awaited<ReturnType<typeof createSupabaseServerClient>>,slug:string,files:File[]){const paths:string[]=[];const urls:string[]=[];for(const file of files){if(!ALLOWED_IMAGE_TYPES.has(file.type))throw new Error('image-type');if(file.size>MAX_IMAGE_SIZE)throw new Error('image-size');const ext=imageExtension(file);if(!ext)throw new Error('image-type');const path=`${slug}/${crypto.randomUUID()}.${ext}`;const{error}=await supabase.storage.from(PRODUCT_IMAGE_BUCKET).upload(path,file,{contentType:file.type,cacheControl:'3600',upsert:false});if(error){if(paths.length)await supabase.storage.from(PRODUCT_IMAGE_BUCKET).remove(paths);throw new Error('image-upload');}paths.push(path);urls.push(supabase.storage.from(PRODUCT_IMAGE_BUCKET).getPublicUrl(path).data.publicUrl);}return{paths,urls};}

export async function setProductPublished(formData:FormData){const supabase=await requireAdmin();const productId=String(formData.get('product_id')??'').trim();const published=String(formData.get('published')??'')==='true';if(!productId)redirect('/admin/products?error=product');const{data:product,error}=await supabase.from('products').update({published}).eq('id',productId).select('slug').single();if(error||!product)redirect('/admin/products?error=publish');revalidatePath('/shop');revalidatePath(`/products/${product.slug}`);revalidatePath('/admin/products');redirect(`/admin/products?${published?'published':'unpublished'}=1`);}

export async function deleteProduct(formData:FormData){
 const supabase=await requireAdmin();const productId=String(formData.get('product_id')??'').trim();if(!productId)redirect('/admin/products?error=delete');
 const{data:product,error:loadError}=await supabase.from('products').select('slug,image_url,image_urls').eq('id',productId).single();if(loadError||!product)redirect('/admin/products?error=delete');
 const gallery=Array.isArray(product.image_urls)?product.image_urls.filter((url):url is string=>typeof url==='string'&&url.length>0):[];const allImages=Array.from(new Set([product.image_url,...gallery].filter((url):url is string=>typeof url==='string'&&url.length>0)));
 const{error:deleteError}=await supabase.from('products').delete().eq('id',productId);if(deleteError)redirect('/admin/products?error=delete');
 const storagePaths=allImages.map(storagePathFromPublicUrl).filter((path):path is string=>!!path);if(storagePaths.length){const{error:storageError}=await supabase.storage.from(PRODUCT_IMAGE_BUCKET).remove(storagePaths);if(storageError)console.error('Product deleted but its Storage images could not be removed:',storageError);}
 revalidatePath('/shop');revalidatePath(`/products/${product.slug}`);revalidatePath('/admin/products');redirect('/admin/products?deleted=1');
}

export async function updateProduct(formData:FormData){
 const supabase=await requireAdmin();const id=String(formData.get('id')??'').trim();const name=String(formData.get('name')??'').trim();const slug=String(formData.get('slug')??'').trim().toLowerCase();const brand=String(formData.get('brand')??'').trim();const category=String(formData.get('category')??'').trim();
 if(!id||!name||!slug||!brand||!category)redirect(`/admin/products/${id}/edit?error=required`);if(!/^[a-z0-9-]+$/.test(slug))redirect(`/admin/products/${id}/edit?error=slug`);
 const files=formData.getAll('image_files').filter((item):item is File=>item instanceof File&&item.size>0);if(files.length>MAX_PRODUCT_IMAGES)redirect(`/admin/products/${id}/edit?error=image-count`);
 let uploaded:{paths:string[];urls:string[]}={paths:[],urls:[]};try{uploaded=await uploadImages(supabase,slug,files);}catch(e){const reason=e instanceof Error?e.message:'image-upload';redirect(`/admin/products/${id}/edit?error=${reason}`);}
 const allExisting=String(formData.get('existing_images')??'').split('\n').map(v=>v.trim()).filter(Boolean);
 const keptExisting=formData.getAll('keep_image').map(v=>String(v)).filter(url=>allExisting.includes(url));
 const removedExisting=allExisting.filter(url=>!keptExisting.includes(url));
 const imageUrls=[...keptExisting,...uploaded.urls];
 if(imageUrls.length>MAX_PRODUCT_IMAGES){if(uploaded.paths.length)await supabase.storage.from(PRODUCT_IMAGE_BUCKET).remove(uploaded.paths);redirect(`/admin/products/${id}/edit?error=image-count`);}
 const priceOnRequest=formData.get('price_on_request')==='on';const specifications=String(formData.get('specifications')??'').split('\n').map(v=>v.trim()).filter(Boolean);
 const{error}=await supabase.from('products').update({name,slug,brand,category,sku:optionalText(formData.get('sku')),badge:optionalText(formData.get('badge')),short_description:optionalText(formData.get('short_description')),description:optionalText(formData.get('description')),specifications,price:priceOnRequest?null:optionalNumber(formData.get('price')),old_price:optionalNumber(formData.get('old_price')),price_on_request:priceOnRequest,stock_quantity:Math.max(0,Number(formData.get('stock_quantity')??0)||0),availability:String(formData.get('availability')??'request_availability'),image_url:imageUrls[0]??null,image_urls:imageUrls,image_alt:optionalText(formData.get('image_alt'))||name,featured:formData.get('featured')==='on',published:formData.get('published')==='on',sort_order:Number(formData.get('sort_order')??0)||0}).eq('id',id);
 if(error){if(uploaded.paths.length)await supabase.storage.from(PRODUCT_IMAGE_BUCKET).remove(uploaded.paths);redirect(`/admin/products/${id}/edit?error=${error.code==='23505'?'duplicate':'save'}`);}
 const removedPaths=removedExisting.map(storagePathFromPublicUrl).filter((p):p is string=>!!p);if(removedPaths.length){const{error:removeError}=await supabase.storage.from(PRODUCT_IMAGE_BUCKET).remove(removedPaths);if(removeError)console.error('Failed to remove old product images:',removeError);}
 revalidatePath('/shop');revalidatePath(`/products/${slug}`);revalidatePath('/admin/products');redirect('/admin/products?updated=1');
}

export async function createProduct(formData:FormData){const supabase=await requireAdmin();const name=String(formData.get('name')??'').trim();const slug=String(formData.get('slug')??'').trim().toLowerCase();const brand=String(formData.get('brand')??'').trim();const category=String(formData.get('category')??'').trim();if(!name||!slug||!brand||!category)redirect('/admin/products/new?error=required');if(!/^[a-z0-9-]+$/.test(slug))redirect('/admin/products/new?error=slug');const specifications=String(formData.get('specifications')??'').split('\n').map(v=>v.trim()).filter(Boolean);const priceOnRequest=formData.get('price_on_request')==='on';const files=formData.getAll('image_files').filter((item):item is File=>item instanceof File&&item.size>0);if(files.length>MAX_PRODUCT_IMAGES)redirect('/admin/products/new?error=image-count');let uploaded:{paths:string[];urls:string[]}={paths:[],urls:[]};try{uploaded=await uploadImages(supabase,slug,files);}catch(e){const reason=e instanceof Error?e.message:'image-upload';redirect(`/admin/products/new?error=${reason}`);}const externalImageUrl=optionalText(formData.get('image_url'));const galleryUrls=uploaded.urls.length?uploaded.urls:externalImageUrl?[externalImageUrl]:[];const{error}=await supabase.from('products').insert({name,slug,brand,category,sku:optionalText(formData.get('sku')),short_description:optionalText(formData.get('short_description')),description:optionalText(formData.get('description')),specifications,price:priceOnRequest?null:optionalNumber(formData.get('price')),old_price:optionalNumber(formData.get('old_price')),price_on_request:priceOnRequest,stock_quantity:Math.max(0,Number(formData.get('stock_quantity')??0)||0),availability:String(formData.get('availability')??'request_availability'),image_url:galleryUrls[0]??null,image_urls:galleryUrls,image_alt:optionalText(formData.get('image_alt'))||name,badge:optionalText(formData.get('badge')),featured:formData.get('featured')==='on',published:formData.get('published')==='on',sort_order:Number(formData.get('sort_order')??0)||0});if(error){if(uploaded.paths.length)await supabase.storage.from(PRODUCT_IMAGE_BUCKET).remove(uploaded.paths);redirect(`/admin/products/new?error=${error.code==='23505'?'duplicate':'save'}`);}revalidatePath('/shop');redirect('/admin/products?created=1');}
