import Link from 'next/link';
import { ArrowRight, BadgeCheck, Building2, CheckCircle2, Headphones, Laptop, Monitor, Network, Printer, Ruler, Server, ShieldCheck, ShoppingBag, Wrench } from 'lucide-react';
import { SectionTitle } from '@/components/SectionTitle';
import { ProductCard } from '@/components/ProductCard';
import { ProductVisual } from '@/components/ProductVisual';
import { CustomerServiceHub } from '@/components/CustomerServiceHub';
import { categories, products } from '@/data/catalog';

const categoryIcons:any={laptop:Laptop,printer:Printer,plotter:Ruler,network:Network,storage:Server,monitor:Monitor};
const categoryHref:Record<string,string>={
  'Laptops & PCs':'/shop?category=Laptops#catalog',
  'Printers & MFPs':'/shop?category=Printers#catalog',
  'Plotters & Wide Format':'/shop?category=Plotters#catalog',
  'Networking':'/shop?category=Networking#catalog',
  'Servers & Storage':'/shop?category=Storage#catalog',
  'Monitors & Displays':'/shop?category=Monitors#catalog',
  'UPS & Power':'/shop?category=UPS#catalog',
  'Consumables':'/shop?category=Consumables#catalog',
  'IT Accessories':'/shop?category=Accessories#catalog',
};
const services=['Printer & Plotter Repair','Laptop & PC Support','Installation & Configuration','Warranty & Parts Support','Preventive Maintenance','Corporate AMC'];
const enterprise=['Onsite IT Support','Field Engineering','IMAC Services','Hardware Break / Fix','Device Deployment','Asset & Lifecycle Support'];
const brandLogos=[
  {name:'HP',src:'https://upload.wikimedia.org/wikipedia/commons/a/ad/HP_logo_2012.svg',className:'h-16 w-16'},
  {name:'Lenovo',src:'https://upload.wikimedia.org/wikipedia/commons/b/b8/Lenovo_logo_2015.svg',className:'h-9 w-32'},
  {name:'Dell',src:'https://upload.wikimedia.org/wikipedia/commons/1/18/Dell_logo_2016.svg',className:'h-14 w-24'},
  {name:'Canon',src:'https://upload.wikimedia.org/wikipedia/commons/0/0a/Canon_wordmark.svg',className:'h-10 w-32'},
  {name:'Epson',src:'https://upload.wikimedia.org/wikipedia/commons/1/1a/Epson_logo.svg',className:'h-9 w-32'},
  {name:'Brother',src:'https://upload.wikimedia.org/wikipedia/commons/8/8e/Brother_logo.svg',className:'h-10 w-32'},
  {name:'ASUS',src:'https://upload.wikimedia.org/wikipedia/commons/2/2e/ASUS_Logo.svg',className:'h-9 w-32'},
  {name:'MSI',src:'https://upload.wikimedia.org/wikipedia/commons/2/2e/Micro-Star_International_logo.svg',className:'h-10 w-32'},
];

export default function Home(){return <div id="top">
 <section className="relative overflow-hidden bg-[#061321] text-white">
  <div className="hero-grid absolute inset-0 opacity-40"/>
  <div className="container relative grid min-h-[620px] items-center gap-12 py-16 lg:grid-cols-[1.02fr_.98fr]">
   <div>
    <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.06] px-4 py-2 text-[10px] font-black uppercase tracking-[.18em] text-blue-200">Technology • Printing • Infrastructure • Service</div>
    <h1 className="max-w-3xl text-5xl font-black leading-[.96] tracking-[-.05em] sm:text-6xl lg:text-[70px]">Your Complete <span className="text-[#57a7ff]">Technology</span> Partner.</h1>
    <p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">IT products, professional printing solutions, enterprise infrastructure and field support — from supply and deployment to service and AMC.</p>
    <div className="mt-8 flex flex-wrap gap-3"><Link href="/shop" className="rounded-full bg-[#0b5cff] px-6 py-3.5 font-black text-white shadow-xl shadow-blue-900/30">Shop Products <ArrowRight className="ml-2 inline" size={17}/></Link><Link href="/quote" className="rounded-full bg-[#f47b20] px-6 py-3.5 font-black text-white">Request a Quote</Link><Link href="/service" className="rounded-full border border-white/20 bg-white/10 px-6 py-3.5 font-black text-white">Get Service</Link></div>
    <div className="mt-9 flex flex-wrap gap-x-7 gap-y-3 text-xs font-bold text-slate-400"><span><CheckCircle2 className="mr-1 inline text-blue-400" size={15}/>Genuine products</span><span><CheckCircle2 className="mr-1 inline text-blue-400" size={15}/>After-sales support</span><span><CheckCircle2 className="mr-1 inline text-blue-400" size={15}/>Enterprise capability</span></div>
   </div>
   <div className="relative hidden lg:block"><div className="absolute -inset-12 rounded-full bg-blue-500/20 blur-3xl"/><div className="relative rounded-[2.2rem] border border-white/10 bg-white/[.06] p-7 backdrop-blur-xl"><div className="rounded-[1.7rem] bg-white p-4"><ProductVisual icon="laptop" compact/></div><div className="mt-4 grid grid-cols-3 gap-3"><div className="rounded-2xl bg-[#0b5cff] p-4"><Printer/><p className="mt-7 text-sm font-black">Printing</p></div><div className="rounded-2xl bg-white/10 p-4"><Network/><p className="mt-7 text-sm font-black">Networking</p></div><div className="rounded-2xl bg-[#f47b20] p-4"><Wrench/><p className="mt-7 text-sm font-black">Service</p></div></div></div></div>
  </div>
 </section>
 <section className="border-b bg-white"><div className="container grid gap-0 md:grid-cols-3">{[[BadgeCheck,'Genuine Technology','Products from leading technology brands.'],[ShieldCheck,'Professional Support','Technical expertise beyond the sale.'],[Headphones,'Kuwait Field Capability','Onsite and enterprise service support.']].map(([Icon,title,text])=>{const I=Icon as any;return <div key={title as string} className="flex gap-4 border-slate-100 px-1 py-7 md:border-r md:px-7 first:md:pl-0 last:md:border-0"><I className="shrink-0 text-[#0b5cff]"/><div><b className="text-sm">{title as string}</b><p className="mt-1 text-sm text-slate-500">{text as string}</p></div></div>})}</div></section>
 <section id="products" className="py-20"><div className="container"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><SectionTitle eyebrow="Shop by Category" title="Everything your technology needs" text="A broad IT catalog backed by ProPrint sales, deployment and after-sales expertise."/><Link href="/shop" className="text-sm font-black text-[#0b5cff]">View all products <ArrowRight className="ml-1 inline" size={15}/></Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map(([name,desc,key])=>{const I=categoryIcons[key];return <Link key={name} href={categoryHref[name] || '/shop#catalog'} className="category-card group"><div className="category-icon"><I size={29}/></div><div><h3 className="text-lg font-black">{name}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{desc}</p><span className="mt-4 inline-block text-xs font-black text-[#0b5cff]">Shop category →</span></div></Link>})}</div></div></section>
 <section className="bg-slate-100 py-20"><div className="container"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><SectionTitle eyebrow="Featured Products" title="Popular technology" text="A curated management-demo catalog showing how ProPrint products will be presented online. Final inventory and selling prices can be connected after approval."/><Link href="/shop" className="rounded-full bg-[#061321] px-5 py-3 text-sm font-black text-white shadow-sm transition hover:bg-[#0b5cff]">Shop all products</Link></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0,4).map(p=><ProductCard key={p.slug} product={p}/>)}</div></div></section>
 <section id="solutions" className="py-20"><div className="container"><SectionTitle eyebrow="One ProPrint" title="Products, solutions and support under one roof"/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[[ShoppingBag,'IT Products','Laptops, desktops, accessories, networking, storage and more.','/shop'],[Printer,'Printing & Plotting','Printers, MFPs, plotters, consumables and large-format solutions.','/shop'],[Wrench,'Service Center & AMC','Repairs, installation, maintenance, warranty and support agreements.','/amc'],[Building2,'Enterprise Field Services','Onsite IT, field engineering, deployment and hardware support.','/enterprise']].map(([Icon,title,text,href])=>{const I=Icon as any;return <Link href={href as string} key={title as string} className="division-card"><I size={32}/><h3>{title as string}</h3><p>{text as string}</p><span>Explore <ArrowRight className="inline" size={14}/></span></Link>})}</div></div></section>
 <section id="services" className="bg-[#061321] py-20 text-white"><div className="container grid gap-12 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><SectionTitle eyebrow="ProPrint Service Center" title="We support what we sell — and more." text="Professional technical services for printers, plotters, laptops, PCs and business IT equipment."/><div className="mt-8 grid gap-3 sm:grid-cols-2">{services.map(x=><div key={x} className="rounded-2xl border border-white/10 bg-white/[.05] p-4 text-sm font-bold"><CheckCircle2 className="mr-2 inline text-[#57a7ff]" size={17}/>{x}</div>)}</div><div className="mt-7 flex flex-wrap gap-3"><Link href="/service" className="rounded-full bg-[#0b5cff] px-6 py-3 font-black text-white shadow-sm transition hover:bg-[#094ed6]">Book a Service</Link><Link href="/amc" className="rounded-full bg-[#f47b20] px-6 py-3 font-black text-white shadow-sm transition hover:bg-[#dc6815]">Explore AMC</Link></div></div><div className="rounded-[2rem] border border-white/10 bg-gradient-to-br from-[#0b5cff] to-[#093c8e] p-9"><ShieldCheck size={42}/><h3 className="mt-8 text-3xl font-black">Keep your technology running.</h3><p className="mt-4 leading-7 text-blue-100">Build a support plan around your printers, plotters, PCs or IT infrastructure with preventive maintenance, break/fix and onsite support.</p><div className="mt-8 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-white/10 p-4"><b>01</b><p className="mt-1 text-xs">Prevent</p></div><div className="rounded-2xl bg-white/10 p-4"><b>02</b><p className="mt-1 text-xs">Support</p></div><div className="rounded-2xl bg-white/10 p-4"><b>03</b><p className="mt-1 text-xs">Maintain</p></div></div></div></div></section>
 <section id="enterprise" className="py-20"><div className="container grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><div className="text-[11px] font-black uppercase tracking-[.2em] text-[#0b5cff]">Enterprise IT & Field Services</div><h2 className="mt-3 text-4xl font-black tracking-[-.03em] md:text-5xl">Onsite capability for enterprise environments.</h2><p className="mt-5 max-w-xl leading-7 text-slate-600">Professional onsite IT support, field engineering, hardware services and deployment capability for managed enterprise environments across Kuwait.</p><p className="mt-4 text-sm font-bold text-slate-500">Current enterprise contract experience is represented as capability; client names are displayed only where public branding permission is confirmed.</p><Link href="/enterprise" className="mt-7 inline-flex rounded-full bg-[#0b5cff] px-6 py-3.5 font-black text-white">Explore Enterprise Services <ArrowRight className="ml-2"/></Link></div><div className="grid gap-4 sm:grid-cols-2">{enterprise.map(x=><div key={x} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><Building2 className="text-[#0b5cff]" size={24}/><h3 className="mt-4 font-black">{x}</h3><p className="mt-1 text-sm text-slate-500">Enterprise-ready field capability.</p></div>)}</div></div></section>
 <section id="brands" className="border-y bg-slate-50 py-16"><div className="container"><div className="text-center"><div className="text-[11px] font-black uppercase tracking-[.2em] text-[#0b5cff]">Technology Partners</div><h2 className="mt-3 text-4xl font-black tracking-[-.03em]">Brands We Work With</h2><p className="mt-3 text-slate-500">Trusted global brands. Genuine products. Reliable support.</p></div><div className="mt-10 grid grid-cols-2 gap-4 md:grid-cols-4 lg:grid-cols-8">{brandLogos.map((brand)=><div key={brand.name} className="flex h-32 items-center justify-center rounded-[1.4rem] border border-slate-200 bg-white px-5 shadow-sm transition hover:-translate-y-1 hover:shadow-md"><img src={brand.src} alt={`${brand.name} logo`} className={`${brand.className} max-h-16 max-w-full object-contain`} loading="lazy"/></div>)}</div></div></section>
 <CustomerServiceHub />
 <section id="about" className="py-20"><div className="container rounded-[2rem] bg-[#0b5cff] p-9 text-white md:p-12"><div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><div className="text-[11px] font-black uppercase tracking-[.2em] text-blue-100">Built for Kuwait business</div><h2 className="mt-3 max-w-3xl text-4xl font-black tracking-[-.03em] md:text-5xl">From one device to a complete technology deployment.</h2><p className="mt-4 max-w-2xl text-blue-100">Talk to ProPrint for retail products, corporate procurement, service, AMC or enterprise field support.</p></div><div className="flex flex-wrap gap-3"><Link href="/quote" className="rounded-full border border-white/30 bg-white px-6 py-3.5 font-black text-[#0b5cff] shadow-sm">Request a Quote</Link><Link href="/shop" className="rounded-full bg-[#f47b20] px-6 py-3.5 font-black text-white shadow-sm">Shop Online</Link></div></div></div></section>
 </div>}
