import Link from 'next/link';
import Image from 'next/image';
import { notFound, redirect } from 'next/navigation';
import { ArrowLeft, ShieldCheck, Trash2 } from 'lucide-react';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { updateProduct } from '@/app/admin/products/actions';

const field='mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none focus:border-[#0b5cff]';
const label='text-xs font-black uppercase tracking-wider text-slate-600';
const productCategories=['Computers','Printers & MFPs','Plotters & Wide Format','Networking','Servers & Storage','Accessories'];
export default async function EditProductPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string}>}){
 const{id}=await params;const{error:err}=await searchParams;const supabase=await createSupabaseServerClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/admin/login');const{data:isAdmin}=await supabase.rpc('is_admin');if(!isAdmin)redirect('/admin/login?error=unauthorized');const{data:p}=await supabase.from('products').select('*').eq('id',id).single();if(!p)notFound();
 const images=Array.isArray(p.image_urls)?p.image_urls.filter((v:unknown):v is string=>typeof v==='string'&&!!v):p.image_url?[p.image_url]:[];const messages:Record<string,string>={required:'Product name, slug, brand and category are required.',slug:'Slug can contain only lowercase letters, numbers and hyphens.',duplicate:'That slug or SKU already exists.',save:'The product could not be updated.','image-count':'The gallery can contain up to 5 images.','image-type':'Choose JPG, PNG or WebP images.','image-size':'Each image must be 5 MB or smaller.','image-upload':'The new images could not be uploaded.'};
 const categoryOptions=productCategories.includes(p.category)?productCategories:[p.category,...productCategories];
 return <main className="min-h-[75vh] bg-slate-50 py-12"><div className="container max-w-5xl"><Link href="/admin/products" className="inline-flex items-center gap-2 text-sm font-black text-[#0b5cff]"><ArrowLeft size={16}/> Back to Product Manager</Link><div className="mt-5 rounded-[2rem] bg-[#061321] p-7 text-white"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.2em] text-blue-300"><ShieldCheck size={15}/> Protected ProPrint Admin</div><h1 className="mt-3 text-3xl font-black">Edit Product</h1><p className="mt-2 text-sm text-slate-300">Update product details, stock, pricing, images and publishing status.</p></div>{err&&<div className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{messages[err]??'Could not update product.'}</div>}
 <form action={updateProduct} className="mt-6 space-y-6"><input type="hidden" name="id" value={p.id}/><input type="hidden" name="existing_images" value={images.join('\n')}/>
 <section className="rounded-[2rem] border border-slate-200 bg-white p-6 md:p-8"><h2 className="text-lg font-black">Product Identity</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><div><label className={label}>Product Name *</label><input name="name" required defaultValue={p.name} className={field}/></div><div><label className={label}>Slug *</label><input name="slug" required pattern="[a-z0-9-]+" defaultValue={p.slug} className={field}/></div><div><label className={label}>Brand *</label><input name="brand" required defaultValue={p.brand} className={field}/></div><div><label className={label}>Category *</label><select name="category" required defaultValue={p.category} className={field}>{categoryOptions.map(category=><option key={category} value={category}>{category}</option>)}</select></div><div><label className={label}>SKU</label><input name="sku" defaultValue={p.sku??''} className={field}/></div><div><label className={label}>Badge</label><input name="badge" defaultValue={p.badge??''} className={field}/></div></div></section>
 <section className="rounded-[2rem] border border-slate-200 bg-white p-6 md:p-8"><h2 className="text-lg font-black">Price & Availability</h2><div className="mt-5 grid gap-5 md:grid-cols-3"><div><label className={label}>Selling Price (KD)</label><input name="price" type="number" min="0" step="0.001" defaultValue={p.price??''} className={field}/></div><div><label className={label}>Old Price (KD)</label><input name="old_price" type="number" min="0" step="0.001" defaultValue={p.old_price??''} className={field}/></div><div><label className={label}>Stock Quantity</label><input name="stock_quantity" type="number" min="0" defaultValue={p.stock_quantity} className={field}/></div><div className="md:col-span-2"><label className={label}>Availability</label><select name="availability" defaultValue={p.availability} className={field}><option value="in_stock">In Stock</option><option value="low_stock">Low Stock</option><option value="available_on_order">Available on Order</option><option value="request_availability">Request Availability</option><option value="out_of_stock">Out of Stock</option><option value="quote_only">Quote Only</option></select></div><label className="flex items-center gap-3 self-end rounded-xl bg-slate-50 px-4 py-3 text-sm font-bold"><input name="price_on_request" type="checkbox" defaultChecked={p.price_on_request}/> Price on request</label></div></section>
 <section className="rounded-[2rem] border border-slate-200 bg-white p-6 md:p-8"><h2 className="text-lg font-black">Product Information</h2><div className="mt-5 space-y-5"><div><label className={label}>Short Description</label><input name="short_description" defaultValue={p.short_description??''} className={field}/></div><div><label className={label}>Full Description</label><textarea name="description" rows={5} defaultValue={p.description??''} className={field}/></div><div><label className={label}>Specifications</label><textarea name="specifications" rows={6} defaultValue={Array.isArray(p.specifications)?p.specifications.join('\n'):''} className={field}/><p className="mt-1 text-xs text-slate-500">One specification per line.</p></div></div></section>
 <section className="rounded-[2rem] border border-slate-200 bg-white p-6 md:p-8"><h2 className="text-lg font-black">Images & Publishing</h2><p className="mt-2 text-sm text-slate-500">Uncheck “Keep image” under any unwanted picture, then click Save Changes. Removed Supabase images will also be deleted from storage.</p>{images.length>0&&<div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-5">{images.map((src:string,i:number)=><div key={src} className="rounded-2xl border border-slate-200 bg-slate-50 p-2"><div className="relative aspect-square overflow-hidden rounded-xl bg-white"><Image src={src} alt={`${p.name} ${i+1}`} fill sizes="160px" className="object-contain p-2"/></div><label className="mt-2 flex cursor-pointer items-center justify-center gap-2 rounded-lg bg-white px-2 py-2 text-xs font-black text-slate-700"><input type="checkbox" name="keep_image" value={src} defaultChecked className="h-4 w-4"/> Keep image</label><div className="mt-1 flex items-center justify-center gap-1 text-[10px] font-bold text-red-600"><Trash2 size={11}/> Uncheck to remove</div></div>)}</div>}
 <div className="mt-5 grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><label className={label}>Add New Gallery Images</label><input name="image_files" type="file" multiple accept="image/jpeg,image/png,image/webp" className={field}/><p className="mt-1 text-xs text-slate-500">New images are added to the pictures you keep. Maximum 5 gallery images total.</p></div><div><label className={label}>Image Alt Text</label><input name="image_alt" defaultValue={p.image_alt??p.name} className={field}/></div><div><label className={label}>Sort Order</label><input name="sort_order" type="number" defaultValue={p.sort_order} className={field}/></div><label className="flex items-center gap-3 rounded-xl bg-slate-50 px-4 py-3 text-sm font-bold"><input name="featured" type="checkbox" defaultChecked={p.featured}/> Featured product</label><label className="flex items-center gap-3 rounded-xl bg-blue-50 px-4 py-3 text-sm font-bold text-[#0b5cff]"><input name="published" type="checkbox" defaultChecked={p.published}/> Published</label></div></section>
 <div className="flex gap-3 pb-8"><button type="submit" className="rounded-full bg-[#0b5cff] px-7 py-3.5 text-sm font-black text-white">Save Changes</button><Link href="/admin/products" className="rounded-full border border-slate-300 bg-white px-7 py-3.5 text-sm font-black text-slate-700">Cancel</Link></div></form></div></main>;
}
