import Link from 'next/link';
import { CheckCircle2, Clock3, Headphones, MapPin, ShieldCheck, Wrench } from 'lucide-react';
import { RequestForm } from '@/components/RequestForm';

const capabilities=['صيانة الطابعات والبلوتر','صيانة أجهزة اللابتوب والكمبيوتر','تشخيص أعطال الأجهزة','التركيب والإعداد','الصيانة الوقائية','دعم الضمان وقطع الغيار','الدعم الفني في مواقع الشركات','عقود الصيانة السنوية AMC'];

export default function ArabicServicePage(){return <main dir="rtl" lang="ar" className="text-right">
<section className="bg-[#061321] py-16 text-white"><div className="container grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><div className="text-[11px] font-black tracking-[.18em] text-blue-200">مركز خدمات ProPrint</div><h1 className="mt-3 text-5xl font-black tracking-[-.04em] md:text-6xl">دعم فني احترافي.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">صيانة وتشخيص وتركيب ودعم للطابعات والبلوتر وأجهزة اللابتوب والكمبيوتر ومعدات الشركات في جميع أنحاء الكويت.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="#request" className="rounded-full bg-[#0b5cff] px-6 py-3.5 font-black text-white">طلب صيانة</Link><Link href="/ar/amc" className="rounded-full bg-[#f47b20] px-6 py-3.5 font-black text-white">استكشف عقود الصيانة</Link></div></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.05] p-5"><Wrench/><h3 className="mt-5 font-black">الصيانة الفنية</h3><p className="mt-2 text-sm leading-6 text-slate-300">تشخيص الأعطال والإصلاح واستبدال القطع.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.05] p-5"><MapPin/><h3 className="mt-5 font-black">الدعم في الموقع</h3><p className="mt-2 text-sm leading-6 text-slate-300">دعم الشركات في مواقع العملاء.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.05] p-5"><Clock3/><h3 className="mt-5 font-black">الصيانة الوقائية</h3><p className="mt-2 text-sm leading-6 text-slate-300">صيانة تساعد على تقليل الأعطال ووقت التوقف.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.05] p-5"><ShieldCheck/><h3 className="mt-5 font-black">تغطية AMC</h3><p className="mt-2 text-sm leading-6 text-slate-300">خطط دعم مستمرة لمعدات الشركات.</p></div></div></div></section>

<section className="py-16"><div className="container"><div className="grid gap-10 lg:grid-cols-[.95fr_1.05fr]"><div><div className="text-[11px] font-black tracking-[.18em] text-[#0b5cff]">قدرات مركز الصيانة</div><h2 className="mt-3 text-4xl font-black tracking-[-.03em]">دعم يستمر بعد البيع.</h2><p className="mt-4 max-w-xl leading-7 text-slate-600">تجمع ProPrint بين الصيانة داخل المركز والدعم الميداني وخدمات الصيانة طويلة الأمد لتوفير شريك تقني واحد للعملاء بعد الشراء.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{capabilities.map(x=><div key={x} className="rounded-2xl border border-slate-200 bg-white p-4 font-bold shadow-sm"><CheckCircle2 className="ml-2 inline text-[#0b5cff]" size={17}/>{x}</div>)}</div></div><div className="rounded-[2rem] bg-slate-100 p-8"><Headphones className="text-[#0b5cff]" size={36}/><h3 className="mt-5 text-2xl font-black">آلية الدعم للشركات</h3><div className="mt-6 space-y-4">{[['01','تسجيل طلب الخدمة'],['02','التشخيص / تعيين الفني'],['03','الإصلاح أو تنفيذ الخدمة في الموقع'],['04','الاختبار وإبلاغ العميل']].map(([n,label])=><div key={n} className="flex items-center gap-4 rounded-2xl bg-white p-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#0b5cff] text-xs font-black text-white">{n}</div><b>{label}</b></div>)}</div></div></div></div></section>

<section id="request" className="scroll-mt-6 bg-slate-50 py-16"><div className="container max-w-5xl"><div className="mb-6 rounded-2xl border border-blue-100 bg-blue-50 px-5 py-4 text-sm font-bold text-slate-700">هل أنت مستعد للمتابعة؟ أكمل طلب الصيانة أدناه لإرسال تفاصيل الجهاز والعطل إلى ProPrint.</div><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><div className="text-[11px] font-black tracking-[.18em] text-[#0b5cff]">هل تحتاج إلى مساعدة؟</div><h2 className="mt-3 text-4xl font-black">طلب صيانة</h2><p className="mt-4 leading-7 text-slate-600">أرسل تفاصيل الجهاز والعطل أدناه. سيقوم الموقع بإنشاء رقم مرجعي لطلب الخدمة.</p></div><RequestForm mode="service"/></div></div></section>
</main>}