import Link from 'next/link';
import { Building2, CheckCircle2, Cpu, HardDrive, Laptop, MapPin, Network, Server, Wrench } from 'lucide-react';

const capabilities=[
  {title:'Onsite IT Support',text:'Field technicians supporting business and enterprise users at customer locations.',icon:MapPin},
  {title:'Hardware Break / Fix',text:'Diagnosis, replacement and repair coordination for supported enterprise hardware.',icon:Wrench},
  {title:'Device Deployment',text:'Rollout support for laptops, desktops, peripherals and workplace technology.',icon:Laptop},
  {title:'IMAC Services',text:'Install, move, add and change activities for managed workplace environments.',icon:Cpu},
  {title:'Infrastructure Support',text:'Selected server, storage and networking support within defined service scope.',icon:Server},
  {title:'Asset Lifecycle Support',text:'Operational assistance across deployment, support, replacement and decommissioning.',icon:HardDrive},
];

export default function EnterprisePage(){return <main>
<section className="bg-[#061321] py-16 text-white"><div className="container grid gap-10 lg:grid-cols-[1fr_.85fr] lg:items-center"><div><div className="text-[11px] font-black uppercase tracking-[.18em] text-blue-200">Enterprise IT & Field Services</div><h1 className="mt-3 text-5xl font-black tracking-[-.04em] md:text-6xl">Onsite capability for enterprise environments.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">Professional field engineering, hardware support, workplace deployment and onsite IT capability for managed service environments across Kuwait.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/quote" className="rounded-full bg-[#0b5cff] px-6 py-3.5 font-black text-white">Corporate Enquiry</Link><Link href="/service" className="rounded-full bg-[#f47b20] px-6 py-3.5 font-black text-white">Request Support</Link></div></div><div className="rounded-[2rem] border border-white/10 bg-white/[.06] p-8"><Building2 size={42}/><h3 className="mt-7 text-3xl font-black">Enterprise-ready delivery.</h3><p className="mt-4 leading-7 text-slate-300">ProPrint can support structured field-service engagements, project deployment and ongoing onsite service within agreed scope and SLA.</p><div className="mt-7 grid grid-cols-2 gap-3">{['Field engineers','Kuwait coverage','Project rollout','Managed support'].map(x=><div key={x} className="rounded-xl bg-white/[.07] p-3 text-xs font-bold">{x}</div>)}</div></div></div></section>

<section className="py-16"><div className="container"><div className="text-[11px] font-black uppercase tracking-[.18em] text-[#0b5cff]">Capabilities</div><h2 className="mt-3 text-4xl font-black tracking-[-.03em]">Field services that extend beyond the service center.</h2><div className="mt-9 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{capabilities.map(({title,text,icon:Icon})=><div key={title} className="rounded-[1.6rem] border border-slate-200 bg-white p-6 shadow-sm"><Icon className="text-[#0b5cff]" size={29}/><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{text}</p></div>)}</div></div></section>

<section className="bg-slate-100 py-16"><div className="container grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><div className="text-[11px] font-black uppercase tracking-[.18em] text-[#0b5cff]">Service delivery model</div><h2 className="mt-3 text-4xl font-black tracking-[-.03em]">Built for structured enterprise support.</h2><p className="mt-4 leading-7 text-slate-600">The public site describes ProPrint's enterprise capability without displaying customer or service-partner names unless public branding permission is confirmed.</p><Link href="/quote" className="mt-7 inline-flex rounded-full bg-[#061321] px-6 py-3.5 font-black text-white">Discuss Enterprise Requirement</Link></div><div className="grid gap-3 sm:grid-cols-2">{['Incident dispatch and onsite response','Hardware diagnostics and replacement coordination','Device rollout and workplace deployment','Project-specific engineering support','Asset moves and lifecycle activity','Service reporting and escalation coordination'].map(x=><div key={x} className="rounded-2xl bg-white p-5 text-sm font-bold shadow-sm"><CheckCircle2 className="mr-2 inline text-[#0b5cff]" size={17}/>{x}</div>)}</div></div></section>

<section className="py-16"><div className="container rounded-[2rem] bg-gradient-to-r from-[#0b5cff] to-[#06439f] p-9 text-white md:flex md:items-center md:justify-between"><div><h2 className="text-3xl font-black">Planning an enterprise rollout or support contract?</h2><p className="mt-2 max-w-2xl text-blue-100">Talk to ProPrint about scope, locations, hardware, service windows and support requirements.</p></div><Link href="/quote" className="mt-6 inline-flex rounded-full bg-[#f47b20] px-6 py-3.5 font-black text-white md:mt-0">Contact Enterprise Team</Link></div></section>
</main>}
